"""Add name to AnswerKey

Revision ID: 3cbcfc66abd9
Revises: 
Create Date: 2024-06-12 15:54:26.003797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbcfc66abd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_key', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
