"""Add exam_id to StudentPaper

Revision ID: 53d4d14cb02d
Revises: c1ea7be493e0
Create Date: 2024-06-13 07:40:03.573026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '53d4d14cb02d'
down_revision = 'c1ea7be493e0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Create the new exam_id column in student_paper with nullable=True
    op.add_column('student_paper',
        sa.Column('exam_id', sa.Integer(), nullable=True)
    )
    
    # Step 2: Set a default value for student_name and student_section before altering the column
    op.execute("UPDATE student_paper SET student_name = 'Unknown' WHERE student_name IS NULL")
    op.execute("UPDATE student_paper SET student_section = 'Unknown' WHERE student_section IS NULL")
    
    # Step 3: Create a foreign key constraint to link the exam_id to the exam table (adjust as needed)
    op.create_foreign_key(
        'fk_student_paper_exam_id',
        'student_paper', 'exam', ['exam_id'], ['id']
    )

    # Step 4: Migrate data to the new column
    op.execute("UPDATE student_paper SET exam_id = 1 WHERE exam_id IS NULL")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_student_paper_exam_id', 'student_paper', type_='foreignkey')
    op.drop_column('student_paper', 'exam_id')
    # ### end Alembic commands ###
