"""Add StudentResult model

Revision ID: 87ef91f647af
Revises: 3cbcfc66abd9
Create Date: 2024-06-12 23:45:45.350558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ef91f647af'
down_revision = '3cbcfc66abd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_paper')
    op.drop_table('student_answer')
    op.drop_table('item_analysis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_analysis',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exam_id', sa.INTEGER(), nullable=False),
    sa.Column('question_number', sa.INTEGER(), nullable=False),
    sa.Column('correct_count', sa.INTEGER(), nullable=True),
    sa.Column('total_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['answer_key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('exam_id', sa.INTEGER(), nullable=False),
    sa.Column('answers', sa.TEXT(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['answer_key.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_paper',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=200), nullable=False),
    sa.Column('answers', sa.BLOB(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('item_analysis', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
