"""Add student name and section to StudentPaper

Revision ID: c1ea7be493e0
Revises: 87ef91f647af
Create Date: 2024-06-13 05:47:59.875220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ea7be493e0'
down_revision = '87ef91f647af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('student_section', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_paper', schema=None) as batch_op:
        batch_op.drop_column('student_section')
        batch_op.drop_column('student_name')

    op.create_table('student_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exam_id', sa.INTEGER(), nullable=False),
    sa.Column('student_answers', sa.TEXT(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('item_analysis', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['answer_key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
